### ISSUE TITLE
2.x backwards compat

### ISSUE THREAD

**Issue by DarkSideGeek** [bpat1434/redmine_category_tree#18]
How does one retrieve a previous version -- which does not have the 3.x prereq -- that will still works on 2.3? There is only a single branch and a single 0.0.6 tag in this repo.

(This is less a bug and more about clarifying github checkouts...)

**Comment by bpat1434** [comment]
I just created a v0.0.5 release which supports 2.x.

**Comment by DarkSideGeek** [comment]
Retrieved and compatibility confirmed. Thanks!
